---
title: "twitter"
author: "Max Weiss"
date: "10/31/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(dplyr)
library(tidyverse)
library(stringr)
library(lubridate)
library(knitr)
library(tidytext)
data("stop_words")

```


```{r scratch, message = FALSE, warning = FALSE}

trump <- read_csv("https://raw.githubusercontent.com/fivethirtyeight/data/master/twitter-ratio/realDonaldTrump.csv")

obama <- read_csv("https://raw.githubusercontent.com/fivethirtyeight/data/master/twitter-ratio/BarackObama.csv")

sens <- read_csv("https://raw.githubusercontent.com/fivethirtyeight/data/master/twitter-ratio/senators.csv")

obama <- obama %>%
  mutate(bioguide_id = NA, party = NA, state = NA)

trump <- trump %>%
  mutate(bioguide_id = NA, party = NA, state = NA)

all_tweets <- rbind(trump, obama, sens)

write.csv(all_tweets, file = "all_tweets.csv") 

twitter <- read_csv("all_tweets.csv")

twitter_clean <- twitter %>%
  select(user, created_at, text, replies, retweets, favorites, party, state) %>%
  mutate(created_at = mdy_hm(created_at),
         party = case_when(party == "D" ~ "Democrat", 
                           party == "R" ~ "Republican",
                           party == "I" ~ "Independent",
                           user == "realDonaldTrump" ~ "Trump")) %>%
  filter(user != "BarackObama", created_at > "2017-01-20" & created_at < "2017-10-20") %>%
  rename("User" = "user", "Time" = "created_at", "Text" = "text", "Replies" = "replies", "Retweets" = "retweets", "Favorites" = "favorites", "Party" = "party", "State" = "state")

summary <- twitter_clean %>%
  group_by(Party) %>%
  summarize("Total Users" = n_distinct(User),
            "Total Tweets" = n(),
            "Average Replies" = round(mean(Replies)),
            "Average Retweets" = round(mean(Retweets)),
            "Average Favorites" = round(mean(Favorites))) %>%
  kable()

```

```{r}

twitter_clean %>%
  unnest_tokens(word, Text) %>%
  anti_join(stop_words) %>%
  count(word) %>%
  arrange(desc(n))



```


```{r}

library(shiny)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(stringr)
library(lubridate)
library(knitr)
twitter_big <- read_csv("all_tweets.csv")

# Define UI for application that plots features of movies
ui <- fluidPage(
  
  titlePanel("Presidential and Senate Twitter Data"),
  
  # Sidebar layout with a input and output definitions
  sidebarLayout(
    
    # Inputs
    sidebarPanel(
      
      sliderInput("bins",
                  "Number of bins:",
                  min = 1,
                  max = 300,
                  value = 30)
    ),
    
    # Outputs
    mainPanel(
      plotOutput(outputId = "densityplot", height = 400),
      plotOutput(outputId = "densityplot2", height = 400),
      tableOutput("summary")
    )
  )
)

# Define server function required to create the scatterplot
server <- function(input, output) {
  
  obama_trump <- twitter_big %>%
    select(created_at, user, retweets) %>%
    mutate(created_at = mdy_hm(created_at)) %>%
    filter(!is.na(created_at), !is.na(user), user %in% c("realDonaldTrump", "BarackObama"))
  
  senators <- twitter_big %>%
    select(-text, -url) %>%
    mutate(created_at = mdy_hm(created_at)) %>%
    filter(!is.na(created_at), !is.na(user), user != "realDonaldTrump", user != "BarackObama") 
  
  senators_table <- senators %>%
    mutate(Party = case_when(party == "D" ~ "Democrat", party == "R" ~ "Republican", party == "I" ~ "Independent")) %>%
    group_by(Party) %>%
    summarize("Total Senators" = n_distinct(user),
              "Total Tweets" = n(),
              "Average Replies" = round(mean(replies)),
              "Average Retweets" = round(mean(retweets)),
              "Average Favorites" = round(mean(favorites)))
  
  output$densityplot <- renderPlot({
    ggplot(senators, aes(x = created_at, fill = party)) +
      theme(plot.title = element_text(hjust = 0.5),
            plot.subtitle = element_text(hjust = 0.5),
            plot.caption = element_text(hjust = 0.5)) + #Center title/subtitle/caption
      labs(title = "Senator Tweeting By Date",
           subtitle = "Separated by Party",
           x = "Date Tweeted", y = "Frequency") + #Create title, subtitle, caption, x/y-axis labels
      guides(fill = guide_legend(title = "Party")) + #Set legend title
      geom_histogram(bins = input$bins)
  })
  
  output$densityplot2 <- renderPlot({
    ggplot(obama_trump, aes(x = created_at, fill = user)) +
      theme(plot.title = element_text(hjust = 0.5),
            plot.subtitle = element_text(hjust = 0.5),
            plot.caption = element_text(hjust = 0.5)) + #Center title/subtitle/caption
      labs(title = "President Tweeting By Date",
           subtitle = "Barack Obama and Donald Trump",
           x = "Date Tweeted", y = "Frequency") + #Create title, subtitle, caption, x/y-axis labels
      guides(fill = guide_legend(title = "President Twitter")) + #Set legend title
      geom_histogram(bins = input$bins)
  })
  
  output$summary <- renderTable({
    senators_table
  })

}

# Create the Shiny app object
shinyApp(ui = ui, server = server)




```




```{r}


library(shiny)
library(tidyverse)
library(stringr)
library(lubridate)
library(knitr)
library(shiny)
library(shinyjs)


ui <- navbarPage("Presidential and Senate Twitter Activity: Trump's First 9 Months in Office",
                 
                 tabPanel("Polling Demographics", fluidPage(
                   
                   # Application title
                   titlePanel("Polling Population Characteristics and Predictive Error")
                
                 )),
                 
                 tabPanel("Polling Demographic", fluidPage(
                   
                   # Application title
                   titlePanel("Polling Population Characteristics and Predictive John")
                   
                 )),
                 
                 tabPanel("Polling Demographiz", fluidPage(
                   
                   # Application title
                   titlePanel("Polling Population Characteristics and Predictive Errorz")
                   
                 )),
                 
                 tabPanel("Polling Demogrs", fluidPage(
                   
                   # Application title
                   titlePanel("Polling Population Characteristics and Predictive Errorsci")
                 ))
                )

# Server
server <- function(input, output) {

}

# Run the application 
shinyApp(ui = ui, server = server)
```
